### ISSUE TITLE
PHP 7.2 as default in beetbox 0.7.0

### ISSUE THREAD

**Issue by bladeaweb** [beetboxvm/beetbox#432]
## Problem/Motivation

> In vagrant after provision, php version sed up as php 7.2, Even after I sed it up to 5.6 in config.

## Expected behaviour

> php version should be like in config.

## Actual behaviour

> php version is 7.2

**Comment by thom8** [comment]
@bladeaweb the default version should be `7.1`, you might need to manually configure your packages if using another version see -- http://docs.drupalvm.com/en/3.5.2/other/php-56/ for more info.

```
 vagrant@beetbox:/var/beetbox/projects/drupal$ php -v
PHP 7.1.8-2+ubuntu16.04.1+deb.sury.org+4 (cli) (built: Aug  4 2017 13:04:12) ( NTS )
```

**Comment by benjy** [comment]
I provisioned a new VM this morning and the default was 7.2 for me also. Even with

    php_version: "7.1"

In my .beetbox/config.yml file I still get 7.2

**Comment by benjy** [comment]
It was only broken on the command line, I fixed this with:

    sudo unlink /etc/alternatives/php
    sudo ln -s /usr/bin/php7.1  /etc/alternatives/php

**Comment by thom8** [comment]
@benjy @bladeaweb still can't seem to replicate this with the latest `0.7.1` box -- would you mind posting a sanitised version of your `config.yml` file?

There also doesn't seem to be any issues raised here yet -- https://github.com/geerlingguy/ansible-role-php/issues

**Comment by benjy** [comment]
I'm using "beet/box": "^0.6.3", so it could be I just need to update the box.

**Comment by thom8** [comment]
`0.6.3` defaults to `5.6` so maybe it only happens when you're upgrading from `5.6` to `7.1`.

As of `0.7.0` the default PHP version is `7.1`

**Comment by bladeaweb** [comment]
@thom8 here is my .beetbox/config.yml file.
```
---
beet_domain: cc.local
beet_root: "{{ beet_base }}/docroot"
php_version: '5.6'
vagrant_memory: '2048'
php_memory_limit: 512M

```
what is wrong and why php still 7.2?

**Comment by thom8** [comment]
@bladeaweb I've created a test branch here -- https://github.com/thom8/beetbox/tree/php5.6

Can you try the following?

```
git clone -b php5.6 https://github.com/thom8/beetbox.git php56-test && cd $_
vagrant up
```

Seems to be OK in CI -->

![image](https://user-images.githubusercontent.com/331453/29166158-a38d2b02-7e08-11e7-8f4c-aab499aeabf8.png)

https://circleci.com/gh/thom8/beetbox/2143

Using this config -- https://github.com/thom8/beetbox/blob/php5.6/.beetbox/config.yml#L28-L34

**Comment by benjy** [comment]
I started a new project today using 0.7.1, it default to 5.6 as you say but then I added

    php_version: "7.1"

Once I re-provisioned. The web php is 7.1 but CLI is now 7.2. My previous comment about unlinking the php version still fixes it.

**Comment by thom8** [comment]
@benjy sounds like an issue with -- https://github.com/geerlingguy/ansible-role-php-versions

So if you downgrade to php 5.6 then upgrade to 7.1, 7.2 is installed.

As `7.1` is the default you can remove the `php_version` from you config, destroy and rebuild and it should be OK.

**Comment by oxyc** [comment]
@benjy could you post the full ansible log output here or over at ansible-role-php-versions?

**Comment by oxyc** [comment]
Guessing this needs to be updated https://github.com/geerlingguy/ansible-role-php-versions/blob/master/tasks/setup-Debian.yml#L49:L51

**Comment by thom8** [comment]
This may need fixing upstream but it's an edge case as it only happens when you downgrade then update.

Workaround is to rebuild with `php_version: "7.1"` or nothing set for `php_version` as `7.1` is the default.

**Comment by BrianGilbert** [comment]
Ran into this issue with clean box build where ```php_version: "7.1"``` was declared in config..  Ran following within guest to resolve for myself:
```
sudo update-alternatives --set php /usr/bin/php7.1
sudo update-alternatives --set phar /usr/bin/phar7.1
