### ISSUE TITLE
MacOS High Sierra: NFS filesystem issues

### ISSUE THREAD

**Issue by klonos** [beetboxvm/beetbox#455]
## Problem/Motivation

After upgrading to the latest High Sierra MacOS (and inevitably switching to APFS), I started having various file system related problems. Most notable:

- I would simply `ll` from docroot and files that I have just copied there from Finder would just not show up in the list
- Old instances would work properly (or so I though), but freshly-created ones would throw "weird" errors like this:

```
Drupal\Component\Plugin\Exception\PluginNotFoundException: The "list" plugin does not exist. in Drupal\Core\Plugin\DefaultPluginManager->doGetDefinition() (line 52 of /var/beetbox/docroot/ 
```

https://github.com/acquia/lightning/issues/455

## Expected behaviour

I expect my instances to work without "funny" file system problems that I then have to spend hours troubleshooting.

## Actual behaviour

Files that exist on the host do not get listed in the guest.

## Steps to reproduce

1. Upgrade to MacOS High Sierra.
2. Fire up a new instance.
3. From your host/Finder, copy a file to your docroot (a sql dump for example)
4. `vagrant ssh`
5. `ll` -> all files are listed, but the file you have copied from step 3 above is not.

## Proposed changes

...FWIW, this workaround has worked for me: https://github.com/hashicorp/vagrant/issues/8788#issuecomment-335260145

## Related:

https://github.com/hashicorp/vagrant/issues/8788
https://github.com/geerlingguy/drupal-vm/issues/1547
http://www.qed42.com/blog/macos-sierra-issues-vagrant

**Comment by klonos** [comment]
...FWIW, this workaround has worked for me: https://github.com/hashicorp/vagrant/issues/8788#issuecomment-335260145

**Comment by thom8** [comment]
@klonos hopefully Vagrant will provide an upstream fix, until then I'm not upgrading, but you're welcome to propose a PR for a fix.

**Comment by klonos** [comment]
@thom8 what I have is just a workaround that is on the host OS level (creating a disk image that uses Mac OS Extended (Journaled) file system instead of the new APFS that comes with High Sierra). So nothing that can be provided in the form of a PR.

I understand that this is an upstream issue. I just wanted to save some time for people that have the same problem and come to the issue queue. I hope that the links to the related tickets provide them with some a clues and pointers as to how to work around their issues until this is addressed.

I hope that you don't find this too much "noise".

**Comment by thom8** [comment]
All good to log the issue! -- just making sure you weren't waiting for a fix from my end as we can't create a code fix for that workaround.

**Comment by thom8** [comment]
Apparently, this issue has been resolved in the latest OS fixes, can anyone confirm?

**Comment by mpriscella** [comment]
@thom8 Upgraded to High Sierra v10.13.1 and am still experiencing this issue, I'd still hold off on upgrading if you haven't already!

**Comment by thom8** [comment]
Thanks @mpriscella, I normally wait to the last minute for any OS updates to my work machine.

Been the guinea pig too many times before ;)

**Comment by klonos** [comment]
Just wanted to report that I am on High Sierra 10.13.3 for some weeks now, and the problem seems to have been sorted for me. If we can have another person verify this, I think that it would be safe to close this ticket. @mpriscella ??

**Comment by mpriscella** [comment]
@klonos Yep, I've been on High Sierra 10.13.3 for a while now and am no longer experiencing this issue. I'd call it safe to close!

**Comment by thom8** [comment]
Thanks for confirming 👍
